// Mocks generated by Mockito 5.4.6 from annotations
// in verasso/test/core/services/mesh_sync_stress_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:verasso/core/mesh/models/mesh_packet.dart' as _i2;
import 'package:verasso/core/services/bluetooth_mesh_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMeshPacket_0 extends _i1.SmartFake implements _i2.MeshPacket {
  _FakeMeshPacket_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BluetoothMeshService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBluetoothMeshService extends _i1.Mock
    implements _i3.BluetoothMeshService {
  MockBluetoothMeshService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<List<String>> get connectedDevicesStream => (super.noSuchMethod(
        Invocation.getter(#connectedDevicesStream),
        returnValue: _i4.Stream<List<String>>.empty(),
      ) as _i4.Stream<List<String>>);

  @override
  int get connectedEndpointsCount => (super.noSuchMethod(
        Invocation.getter(#connectedEndpointsCount),
        returnValue: 0,
      ) as int);

  @override
  List<String> get expertise => (super.noSuchMethod(
        Invocation.getter(#expertise),
        returnValue: <String>[],
      ) as List<String>);

  @override
  bool get isMeshActive => (super.noSuchMethod(
        Invocation.getter(#isMeshActive),
        returnValue: false,
      ) as bool);

  @override
  _i4.Stream<_i2.MeshPacket> get meshStream => (super.noSuchMethod(
        Invocation.getter(#meshStream),
        returnValue: _i4.Stream<_i2.MeshPacket>.empty(),
      ) as _i4.Stream<_i2.MeshPacket>);

  @override
  int get trustThreshold => (super.noSuchMethod(
        Invocation.getter(#trustThreshold),
        returnValue: 0,
      ) as int);

  @override
  _i4.Future<void> broadcastPacket(
    _i2.MeshPayloadType? type,
    Map<String, dynamic>? payload, {
    String? targetSubject,
    _i2.MeshPriority? priority,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #broadcastPacket,
          [
            type,
            payload,
          ],
          {
            #targetSubject: targetSubject,
            #priority: priority,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> initialize(
    String? userName,
    String? userId, {
    List<String>? expertise = const [],
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [
            userName,
            userId,
          ],
          {#expertise: expertise},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void setExpertise(List<String>? areas) => super.noSuchMethod(
        Invocation.method(
          #setExpertise,
          [areas],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setPulsedMode(bool? enabled) => super.noSuchMethod(
        Invocation.method(
          #setPulsedMode,
          [enabled],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setTrustThreshold(int? threshold) => super.noSuchMethod(
        Invocation.method(
          #setTrustThreshold,
          [threshold],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<bool> startAdvertising() => (super.noSuchMethod(
        Invocation.method(
          #startAdvertising,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> startDiscovery() => (super.noSuchMethod(
        Invocation.method(
          #startDiscovery,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> stopAdvertising() => (super.noSuchMethod(
        Invocation.method(
          #stopAdvertising,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void stopAll() => super.noSuchMethod(
        Invocation.method(
          #stopAll,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> stopDiscovery() => (super.noSuchMethod(
        Invocation.method(
          #stopDiscovery,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [MeshPacket].
///
/// See the documentation for Mockito's code generation for more information.
class MockMeshPacket extends _i1.Mock implements _i2.MeshPacket {
  MockMeshPacket() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#id),
        ),
      ) as String);

  @override
  String get senderId => (super.noSuchMethod(
        Invocation.getter(#senderId),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#senderId),
        ),
      ) as String);

  @override
  String get senderName => (super.noSuchMethod(
        Invocation.getter(#senderName),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#senderName),
        ),
      ) as String);

  @override
  _i2.MeshPayloadType get type => (super.noSuchMethod(
        Invocation.getter(#type),
        returnValue: _i2.MeshPayloadType.handshake,
      ) as _i2.MeshPayloadType);

  @override
  Map<String, dynamic> get payload => (super.noSuchMethod(
        Invocation.getter(#payload),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  int get trustScore => (super.noSuchMethod(
        Invocation.getter(#trustScore),
        returnValue: 0,
      ) as int);

  @override
  String get timestamp => (super.noSuchMethod(
        Invocation.getter(#timestamp),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#timestamp),
        ),
      ) as String);

  @override
  List<String> get seenBy => (super.noSuchMethod(
        Invocation.getter(#seenBy),
        returnValue: <String>[],
      ) as List<String>);

  @override
  int get ttl => (super.noSuchMethod(
        Invocation.getter(#ttl),
        returnValue: 0,
      ) as int);

  @override
  _i2.MeshPriority get priority => (super.noSuchMethod(
        Invocation.getter(#priority),
        returnValue: _i2.MeshPriority.low,
      ) as _i2.MeshPriority);

  @override
  _i2.MeshPacket copyWith({
    String? signature,
    String? publicKey,
    int? ttl,
    List<String>? seenBy,
    String? identityProof,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #copyWith,
          [],
          {
            #signature: signature,
            #publicKey: publicKey,
            #ttl: ttl,
            #seenBy: seenBy,
            #identityProof: identityProof,
          },
        ),
        returnValue: _FakeMeshPacket_0(
          this,
          Invocation.method(
            #copyWith,
            [],
            {
              #signature: signature,
              #publicKey: publicKey,
              #ttl: ttl,
              #seenBy: seenBy,
              #identityProof: identityProof,
            },
          ),
        ),
      ) as _i2.MeshPacket);

  @override
  Map<String, dynamic> toMap() => (super.noSuchMethod(
        Invocation.method(
          #toMap,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);
}
