enum QuestCategory {
  social,
  explore,
  culture,
  wellness,
  creative,
  adventure,
  food,
  random,
}

class Quest {
  final String id;
  final String title;
  final String description;
  final String photoPrompt;
  final int xp;
  final QuestCategory category;
  final String emoji;

  Quest({
    required this.id,
    required this.title,
    required this.description,
    required this.photoPrompt,
    required this.xp,
    required this.category,
    required this.emoji,
  });
}

// 160 Hand-crafted daily sidequests for Verasso
final List<Quest> questPool = [
  // ─── SOCIAL (20) ─────────────────────────────────────────────────────────────
  Quest(id: 'soc_01', title: 'Talk to a Stranger', description: 'Start a genuine conversation with someone you\'ve never met. Bus stop, chai stall, anywhere.', photoPrompt: 'Photo of the place where it happened', xp: 150, category: QuestCategory.social, emoji: '🗣️'),
  Quest(id: 'soc_02', title: 'Call Someone You Miss', description: 'Not a text. A voice call. Ring someone you haven\'t spoken to in 3+ months.', photoPrompt: 'Screenshot of the call duration', xp: 100, category: QuestCategory.social, emoji: '📞'),
  Quest(id: 'soc_03', title: 'A Genuine Compliment', description: 'Tell the person running a small shop or a stranger something genuinely nice.', photoPrompt: 'Photo of what you complimented (or the shop)', xp: 75, category: QuestCategory.social, emoji: '🤝'),
  Quest(id: 'soc_04', title: 'Buy a Coffee for the Next Person', description: 'Pay for the chai/coffee of the person behind you in line.', photoPrompt: 'Photo of the receipt or the cup', xp: 200, category: QuestCategory.social, emoji: '☕'),
  Quest(id: 'soc_05', title: 'Help Someone Carry Something', description: 'Offer to help someone struggling with a heavy bag or item.', photoPrompt: 'A thumbs up selfie afterwards', xp: 120, category: QuestCategory.social, emoji: '🤲'),
  Quest(id: 'soc_06', title: 'Re-connect with a Teacher', description: 'Send a message or email (or call) a teacher who genuinely helped you.', photoPrompt: 'Screenshot of the message sent', xp: 150, category: QuestCategory.social, emoji: '🎓'),
  Quest(id: 'soc_07', title: 'Leave a Positive Note', description: 'Write a positive, encouraging note and leave it somewhere public (library, bus seat).', photoPrompt: 'Photo of the note where you left it', xp: 90, category: QuestCategory.social, emoji: '📝'),
  Quest(id: 'soc_08', title: 'Strike up a Chat with Security', description: 'Ask the guard / watchman of a building how their day is going. Listen.', photoPrompt: 'Photo of the gate / building exterior', xp: 80, category: QuestCategory.social, emoji: '🛡️'),
  Quest(id: 'soc_09', title: 'Thank Your Parents', description: 'Just tell them thank you for something specific they did for you recently.', photoPrompt: 'Photo with them (or of the text message)', xp: 100, category: QuestCategory.social, emoji: '❤️'),
  Quest(id: 'soc_10', title: 'High Five a Friend', description: 'Give a friend an incredibly enthusiastic high-five for absolutely no reason.', photoPrompt: 'Action shot of the high five', xp: 50, category: QuestCategory.social, emoji: '🙌'),
  Quest(id: 'soc_11', title: 'Hold the Door', description: 'Wait and hold the door open for someone trailing behind you.', photoPrompt: 'Photo of the door', xp: 40, category: QuestCategory.social, emoji: '🚪'),
  Quest(id: 'soc_12', title: 'Recommend a Song', description: 'Tell a friend they MUST listen to a specific song because it made you think of them.', photoPrompt: 'Screenshot of the song / message', xp: 60, category: QuestCategory.social, emoji: '🎵'),
  Quest(id: 'soc_13', title: 'Ask for Advice', description: 'Ask someone older than you for advice on a problem you are facing.', photoPrompt: 'Photo of where you had the chat', xp: 110, category: QuestCategory.social, emoji: '🦉'),
  Quest(id: 'soc_14', title: 'Support a Small Creator', description: 'Leave a genuinely thoughtful comment (not just an emoji) on a small creator\'s post.', photoPrompt: 'Screenshot of your comment', xp: 70, category: QuestCategory.social, emoji: '💬'),
  Quest(id: 'soc_15', title: 'Teach Someone Something Small', description: 'Show someone a cool shortcut, trick, or fact they didn\'t know.', photoPrompt: 'Photo of the person / thing you taught', xp: 90, category: QuestCategory.social, emoji: '🧠'),
  Quest(id: 'soc_16', title: 'Give up Your Seat', description: 'Stand up so someone else can sit down on public transport or a waiting area.', photoPrompt: 'Photo of you standing', xp: 100, category: QuestCategory.social, emoji: '🪑'),
  Quest(id: 'soc_17', title: 'Ask "How are you really?"', description: 'Push past the default "I\'m fine" and ask a friend how they are actually doing.', photoPrompt: 'A photo of the two of you', xp: 130, category: QuestCategory.social, emoji: '💔'),
  Quest(id: 'soc_18', title: 'Introduce Two Friends', description: 'Connect two people from different circles who you think would get along.', photoPrompt: 'A screenshot of the intro text/group', xp: 120, category: QuestCategory.social, emoji: '🔗'),
  Quest(id: 'soc_19', title: 'Leave a 5-Star Review', description: 'Find a local business you love on maps and write a detailed 5-star review.', photoPrompt: 'Screenshot of the published review', xp: 85, category: QuestCategory.social, emoji: '⭐'),
  Quest(id: 'soc_20', title: 'Return a Lost Item', description: 'If you spot something dropped, catch up to the person and return it. (If you don\'t spot anything, pick up a piece of litter instead.)', photoPrompt: 'Photo of the returned item (or picked up litter)', xp: 150, category: QuestCategory.social, emoji: '🔍'),

  // ─── EXPLORE (20) ────────────────────────────────────────────────────────────
  Quest(id: 'exp_01', title: 'New Café Visit', description: 'Sit down at a café or stall you\'ve never visited. Stay at least 20 mins.', photoPrompt: 'Photo of the place or your drink', xp: 120, category: QuestCategory.explore, emoji: '☕'),
  Quest(id: 'exp_02', title: 'The Unknown Route', description: 'Get off one stop early or take a completely different street walking home.', photoPrompt: 'Photo of something interesting on the new route', xp: 80, category: QuestCategory.explore, emoji: '🚶'),
  Quest(id: 'exp_03', title: 'Ancient Architecture', description: 'Find a building or structure in your area that is older than you are.', photoPrompt: 'Photo of the old structure', xp: 100, category: QuestCategory.explore, emoji: '🏛️'),
  Quest(id: 'exp_04', title: 'Find Street Art', description: 'Locate a mural, interesting graffiti, or street art you haven\'t paid attention to.', photoPrompt: 'Photo of the artwork', xp: 70, category: QuestCategory.explore, emoji: '🎨'),
  Quest(id: 'exp_05', title: 'The Highest Point', description: 'Get to the highest physically accessible public point in your immediate area and look down.', photoPrompt: 'Photo of the view looking down', xp: 150, category: QuestCategory.explore, emoji: '⛰️'),
  Quest(id: 'exp_06', title: 'Visit a Public Library', description: 'Walk into a public/uni library. Walk the aisles. Read the title of the dustiest book.', photoPrompt: 'Photo inside the library', xp: 110, category: QuestCategory.explore, emoji: '📚'),
  Quest(id: 'exp_07', title: 'Find a Hidden Alley', description: 'Walk down an alleyway or a side-street that you usually walk straight past.', photoPrompt: 'Photo looking down the alley', xp: 90, category: QuestCategory.explore, emoji: '🧱'),
  Quest(id: 'exp_08', title: 'The Local Monument', description: 'Visit a local statue, plaque, or monument. Actually read what is inscribed on it.', photoPrompt: 'Photo of the inscription', xp: 85, category: QuestCategory.explore, emoji: '🗽'),
  Quest(id: 'exp_09', title: 'Market Chaos', description: 'Walk through the busiest local market or bazaar nearby, just observing.', photoPrompt: 'Photo capturing the crowd/chaos', xp: 100, category: QuestCategory.explore, emoji: '🛒'),
  Quest(id: 'exp_10', title: 'Follow a Cat', description: 'Spot a street cat and see where it goes (without bothering it).', photoPrompt: 'Photo of the cat on its journey', xp: 120, category: QuestCategory.explore, emoji: '🐈'),
  Quest(id: 'exp_11', title: 'Public Transport Roulette', description: 'Take a bus or train headed in a safe but random direction for 3 stops. Then come back.', photoPrompt: 'Photo out the window of the vehicle', xp: 160, category: QuestCategory.explore, emoji: '🚌'),
  Quest(id: 'exp_12', title: 'Find Water', description: 'Locate the nearest natural (or artificial) body of water. A river, lake, pond, or large fountain.', photoPrompt: 'Photo of the water', xp: 95, category: QuestCategory.explore, emoji: '💧'),
  Quest(id: 'exp_13', title: 'Spot a Strange Car', description: 'Find a vintage, wildly painted, or incredibly strange vehicle parked somewhere.', photoPrompt: 'Photo of the car', xp: 60, category: QuestCategory.explore, emoji: '🚗'),
  Quest(id: 'exp_14', title: 'Look for Neon', description: 'Go out after dark and find a glowing neon sign (not an LED screen).', photoPrompt: 'Photo of the neon sign', xp: 75, category: QuestCategory.explore, emoji: '🚥'),
  Quest(id: 'exp_15', title: 'The Boundary', description: 'Walk straight until you hit the edge of your neighborhood/district boundary.', photoPrompt: 'Photo of the boundary sign or crossing', xp: 130, category: QuestCategory.explore, emoji: '🗺️'),
  Quest(id: 'exp_16', title: 'Botanical Observation', description: 'Find the largest tree in a 1km radius and stand under it for 2 minutes.', photoPrompt: 'Photo looking up through the branches', xp: 80, category: QuestCategory.explore, emoji: '🌳'),
  Quest(id: 'exp_17', title: 'Find a Rooftop', description: 'Gain access to a safe rooftop view and observe the skyline.', photoPrompt: 'Photo from the roof', xp: 140, category: QuestCategory.explore, emoji: '🏢'),
  Quest(id: 'exp_18', title: 'Track the Train', description: 'Find a spot where you can safely watch a train pass by.', photoPrompt: 'Photo of the train passing', xp: 110, category: QuestCategory.explore, emoji: '🚂'),
  Quest(id: 'exp_19', title: 'The Oldest Shop', description: 'Find the shop in your area that looks like it hasn\'t been renovated in 40 years.', photoPrompt: 'Photo of the storefront', xp: 90, category: QuestCategory.explore, emoji: '🏪'),
  Quest(id: 'exp_20', title: 'Tourist in your City', description: 'Go to a place only tourists visit in your city, and act like a tourist.', photoPrompt: 'A very touristy selfie at the landmark', xp: 150, category: QuestCategory.explore, emoji: '📸'),

  // ─── CULTURE (20) ────────────────────────────────────────────────────────────
  Quest(id: 'cul_01', title: 'Genre Roulette', description: 'Watch a movie in a genre or language you normally skip.', photoPrompt: 'Photo of your screen with the title', xp: 130, category: QuestCategory.culture, emoji: '🎬'),
  Quest(id: 'cul_02', title: '10 Random Pages', description: 'Pick something off a shelf (library, shop, friend\'s house) and read 10 pages.', photoPrompt: 'Photo of the specific page you read', xp: 90, category: QuestCategory.culture, emoji: '📖'),
  Quest(id: 'cul_03', title: 'Full Album Listen', description: 'Listen to an entire album start to finish. No skips.', photoPrompt: 'Screenshot of the album playing', xp: 80, category: QuestCategory.culture, emoji: '🎵'),
  Quest(id: 'cul_04', title: 'Watch a Documentary', description: 'Watch at least a 40-minute documentary on a subject you know zero about.', photoPrompt: 'Photo of the documentary title card', xp: 110, category: QuestCategory.culture, emoji: '🌍'),
  Quest(id: 'cul_05', title: 'Poetry Break', description: 'Find a poem online or in a book, read it out loud to yourself twice.', photoPrompt: 'Screenshot or photo of the poem', xp: 60, category: QuestCategory.culture, emoji: '✒️'),
  Quest(id: 'cul_06', title: 'Learn a Folk Tale', description: 'Read a myth, legend, or folk tale from a culture completely foreign to yours.', photoPrompt: 'Screenshot of what you read', xp: 80, category: QuestCategory.culture, emoji: '🐉'),
  Quest(id: 'cul_07', title: 'Classical Challenge', description: 'Listen to a Mozart, Beethoven, or Bach symphony while doing your chores.', photoPrompt: 'Screenshot of the classical track playing', xp: 70, category: QuestCategory.culture, emoji: '🎻'),
  Quest(id: 'cul_08', title: 'Visit a Museum/Gallery', description: 'Go to a local museum, art gallery, or cultural center even for just 30 mins.', photoPrompt: 'Photo of your favorite exhibit', xp: 200, category: QuestCategory.culture, emoji: '🖼️'),
  Quest(id: 'cul_09', title: 'Foreign News', description: 'Read the front page news from a news outlet from a different continent.', photoPrompt: 'Screenshot of the headline you read', xp: 50, category: QuestCategory.culture, emoji: '📰'),
  Quest(id: 'cul_10', title: 'Silent Film Study', description: 'Watch a short film or sequence from the silent film era (e.g. Charlie Chaplin) on YouTube.', photoPrompt: 'Photo of the screen', xp: 90, category: QuestCategory.culture, emoji: '🎥'),
  Quest(id: 'cul_11', title: 'Learn 5 Words', description: 'Learn how to say Hello, Thank You, Sorry, Yes, and No in a new language.', photoPrompt: 'Screenshot of the translation / your notes', xp: 80, category: QuestCategory.culture, emoji: '🌐'),
  Quest(id: 'cul_12', title: 'Analyze a Painting', description: 'Stare at a famous painting online for 3 straight minutes. Just look at the details.', photoPrompt: 'Screenshot of the painting', xp: 60, category: QuestCategory.culture, emoji: '🧑‍🎨'),
  Quest(id: 'cul_13', title: 'Stand-up Special', description: 'Watch a stand-up comedy special from a comedian you have never heard of.', photoPrompt: 'Photo of the comedian on your screen', xp: 100, category: QuestCategory.culture, emoji: '🎤'),
  Quest(id: 'cul_14', title: 'Read the Credits', description: 'Next time you finish an episode or movie today, sit and watch the entire credits roll.', photoPrompt: 'Photo of the scrolling credits', xp: 50, category: QuestCategory.culture, emoji: '📜'),
  Quest(id: 'cul_15', title: 'Wiki Rabbit Hole', description: 'Hit "Random Article" on Wikipedia 5 times. Read the 5th article completely.', photoPrompt: 'Screenshot of the 5th article', xp: 75, category: QuestCategory.culture, emoji: '🕳️'),
  Quest(id: 'cul_16', title: 'Indie Game Time', description: 'Play a small, free indie game (on itch.io or mobile) made by a solo dev.', photoPrompt: 'Photo of the game running', xp: 120, category: QuestCategory.culture, emoji: '🕹️'),
  Quest(id: 'cul_17', title: 'Read a Comic/Manga', description: 'Read the first chapter of a highly rated comic graphic novel or manga.', photoPrompt: 'Photo of a panel you liked', xp: 85, category: QuestCategory.culture, emoji: '🗯️'),
  Quest(id: 'cul_18', title: 'Instrumental Only', description: 'Do your next 1-hour study or work session listening strictly to Video Game OSTs.', photoPrompt: 'Screenshot of the playlist', xp: 70, category: QuestCategory.culture, emoji: '🎧'),
  Quest(id: 'cul_19', title: 'Look up an Architect', description: 'Find the name of the architect who designed a famous building in your nation and read their bio.', photoPrompt: 'Screenshot of the architect\'s face', xp: 80, category: QuestCategory.culture, emoji: '📐'),
  Quest(id: 'cul_20', title: 'Vintage Advertisements', description: 'Look up and watch 3 television commercials from the 1990s or earlier.', photoPrompt: 'Screenshot of the retro commercial', xp: 55, category: QuestCategory.culture, emoji: '📺'),

  // ─── WELLNESS (20) ───────────────────────────────────────────────────────────
  Quest(id: 'wel_01', title: 'Observe the Sky', description: 'Watch a full sunrise or sunset with your phone entirely put away.', photoPrompt: 'Photo of the sky taken AFTER you watched it', xp: 200, category: QuestCategory.wellness, emoji: '🌅'),
  Quest(id: 'wel_02', title: 'Cook a Meal', description: 'Cook a meal entirely from scratch. No instant noodles.', photoPrompt: 'Photo of the finished dish', xp: 150, category: QuestCategory.wellness, emoji: '🍳'),
  Quest(id: 'wel_03', title: 'Sit Outside', description: 'Sit outside for 30 minutes doing absolutely nothing. No phone, no music. Just exist.', photoPrompt: 'Photo of the view from where you sat', xp: 180, category: QuestCategory.wellness, emoji: '🌳'),
  Quest(id: 'wel_04', title: 'Digital Detox Hour', description: 'Turn off your phone, laptop, and TV for 60 full minutes.', photoPrompt: 'Photo of a clock or watch (device off)', xp: 140, category: QuestCategory.wellness, emoji: '📵'),
  Quest(id: 'wel_05', title: 'Stretch Session', description: 'Do 15 minutes of slow, intentional stretching or yoga.', photoPrompt: 'Photo of your stretching mat or space', xp: 100, category: QuestCategory.wellness, emoji: '🧘'),
  Quest(id: 'wel_06', title: 'Drink 3L of Water', description: 'Track your water intake today and hit 3 liters.', photoPrompt: 'Photo of your final empty glass/bottle', xp: 90, category: QuestCategory.wellness, emoji: '🚰'),
  Quest(id: 'wel_07', title: 'A Long Walk', description: 'Go for a walk with no destination for at least 45 minutes.', photoPrompt: 'A photo taken at the furthest point of your walk', xp: 130, category: QuestCategory.wellness, emoji: '👟'),
  Quest(id: 'wel_08', title: 'Clean your Room', description: 'Pick up every piece of trash, fold the clothes, make the bed. Reset your space.', photoPrompt: 'Photo of the sparkling clean room', xp: 160, category: QuestCategory.wellness, emoji: '🧹'),
  Quest(id: 'wel_09', title: 'No Sugar Day', description: 'Consume zero processed sugar for an entire day (fruits are fine).', photoPrompt: 'Photo of your healthy final meal of the day', xp: 150, category: QuestCategory.wellness, emoji: '🚫🍩'),
  Quest(id: 'wel_10', title: 'Read Before Sleep', description: 'Instead of scrolling before bed, read a physical book for 20 minutes.', photoPrompt: 'Photo of the book on your pillow', xp: 110, category: QuestCategory.wellness, emoji: '🛌'),
  Quest(id: 'wel_11', title: 'Cold Shower', description: 'Take a shower on the coldest possible setting for the last 2 minutes.', photoPrompt: 'A selfie wrapped in a towel looking freezing', xp: 140, category: QuestCategory.wellness, emoji: '🚿'),
  Quest(id: 'wel_12', title: 'Declutter 5 Items', description: 'Find 5 things in your room you don\'t need. Donate or trash them.', photoPrompt: 'Photo of the 5 items leaving your life', xp: 100, category: QuestCategory.wellness, emoji: '📦'),
  Quest(id: 'wel_13', title: 'Meditation', description: 'Sit in a quiet room, close your eyes, and focus purely on your breath for 10 minutes.', photoPrompt: 'Photo of the quiet space you used', xp: 120, category: QuestCategory.wellness, emoji: '🧘‍♂️'),
  Quest(id: 'wel_14', title: 'Sunlight Exposure', description: 'Get 15 minutes of direct morning sunlight on your skin and eyes.', photoPrompt: 'Photo looking out at the morning sun', xp: 80, category: QuestCategory.wellness, emoji: '☀️'),
  Quest(id: 'wel_15', title: 'No Caffeine', description: 'Skip the coffee and energy drinks today. Survive on water and tea only.', photoPrompt: 'Photo of your herbal tea or water glass', xp: 130, category: QuestCategory.wellness, emoji: '🍵'),
  Quest(id: 'wel_16', title: 'Write down 3 Worries', description: 'Write down the 3 things stressing you out most. Then physically tear up the paper.', photoPrompt: 'Photo of the torn up pieces', xp: 70, category: QuestCategory.wellness, emoji: '🗑️'),
  Quest(id: 'wel_17', title: 'Bake Something', description: 'Bake a cake, cookies, or bread. The smell alone is wellness.', photoPrompt: 'Photo of the baked goods baking in the oven', xp: 120, category: QuestCategory.wellness, emoji: '🧁'),
  Quest(id: 'wel_18', title: 'Barefoot on Grass', description: 'Take your shoes off and stand fully barefoot on natural grass or earth for 5 minutes.', photoPrompt: 'Photo of your bare feet on the ground', xp: 90, category: QuestCategory.wellness, emoji: '🌱'),
  Quest(id: 'wel_19', title: 'Fix Your Posture', description: 'For the next hour, consciously correct your posture every time you notice yourself slouching.', photoPrompt: 'A very stiff, weirdly straight posture selfie', xp: 60, category: QuestCategory.wellness, emoji: '📏'),
  Quest(id: 'wel_20', title: 'Unsubscribe', description: 'Go to your email and unsubscribe from 10 annoying newsletters or promo lists.', photoPrompt: 'Screenshot of the finalized unsubscribes', xp: 80, category: QuestCategory.wellness, emoji: '📧'),

  // ─── CREATIVE (20) ───────────────────────────────────────────────────────────
  Quest(id: 'cre_01', title: 'Draw Something', description: 'It doesn\'t matter if it\'s bad. Draw something you see right now.', photoPrompt: 'Photo of your drawing', xp: 100, category: QuestCategory.creative, emoji: '✏️'),
  Quest(id: 'cre_02', title: '3 Honest Sentences', description: 'Write 3 honest sentences about today. Not for anyone else to read.', photoPrompt: 'Photo of the notebook page (blur if needed)', xp: 70, category: QuestCategory.creative, emoji: '📝'),
  Quest(id: 'cre_03', title: 'The Mundane Photo', description: 'Photograph something mundane (a cup, a chair) but make it look incredibly dramatic.', photoPrompt: 'The dramatic photo', xp: 80, category: QuestCategory.creative, emoji: '📸'),
  Quest(id: 'cre_04', title: 'Origami Crane', description: 'Look up a tutorial and fold a paper crane or boat.', photoPrompt: 'Photo of your origami creation', xp: 90, category: QuestCategory.creative, emoji: '🦢'),
  Quest(id: 'cre_05', title: 'Invent a Word', description: 'Invent a new word, write down its definition, and use it in a sentence today.', photoPrompt: 'Screenshot of the word and definition', xp: 60, category: QuestCategory.creative, emoji: '🔤'),
  Quest(id: 'cre_06', title: 'Design a Logo', description: 'Sketch a logo for a fake company or brand you just made up.', photoPrompt: 'Photo of the logo sketch', xp: 110, category: QuestCategory.creative, emoji: '✨'),
  Quest(id: 'cre_07', title: 'Haiku Moment', description: 'Write a 5-7-5 syllable Haiku poem about whatever you are doing right now.', photoPrompt: 'Screenshot of the Haiku', xp: 75, category: QuestCategory.creative, emoji: '⛩️'),
  Quest(id: 'cre_08', title: 'Color Palette', description: 'Find 3 objects near you that form a beautiful color palette and arrange them together.', photoPrompt: 'Photo of the aesthetic arrangement', xp: 85, category: QuestCategory.creative, emoji: '🎨'),
  Quest(id: 'cre_09', title: 'Write with Left Hand', description: 'Write the alphabet out using your non-dominant hand.', photoPrompt: 'Photo of the messy handwriting', xp: 50, category: QuestCategory.creative, emoji: '✍️'),
  Quest(id: 'cre_10', title: 'Macro Photography', description: 'Use your phone to take an extreme close-up (macro) photo of a texture.', photoPrompt: 'The macro photo', xp: 80, category: QuestCategory.creative, emoji: '🔎'),
  Quest(id: 'cre_11', title: 'Record a Voice Note', description: 'Record a 2-minute voice note of your stream of consciousness. Don\'t edit it.', photoPrompt: 'Screenshot of the voice recording app', xp: 90, category: QuestCategory.creative, emoji: '🎙️'),
  Quest(id: 'cre_12', title: 'Doodle a Monster', description: 'Draw a weird little creature or monster on the margin of your notes.', photoPrompt: 'Photo of the doodle', xp: 65, category: QuestCategory.creative, emoji: '👾'),
  Quest(id: 'cre_13', title: 'Rearrange Your Room', description: 'Move at least one major piece of furniture in your room to a new spot.', photoPrompt: 'Photo of the new room layout', xp: 150, category: QuestCategory.creative, emoji: '🛏️'),
  Quest(id: 'cre_14', title: 'Short Story Prompt', description: 'Write a paragraph starting with: "The door was locked, but the window was... "', photoPrompt: 'Screenshot or photo of the paragraph', xp: 120, category: QuestCategory.creative, emoji: '📖'),
  Quest(id: 'cre_15', title: 'Create a Playlist', description: 'Create a 10-track playlist around a highly specific mood (e.g., "Villain entering a room").', photoPrompt: 'Screenshot of the playlist', xp: 100, category: QuestCategory.creative, emoji: '🎧'),
  Quest(id: 'cre_16', title: 'Build a House of Cards', description: 'Try to build a house of cards at least 3 levels high.', photoPrompt: 'Photo of the structure (or it falling over)', xp: 110, category: QuestCategory.creative, emoji: '🃏'),
  Quest(id: 'cre_17', title: 'Shadow Puppets', description: 'Use a flashlight to cast a cool shadow puppet on the wall in a dark room.', photoPrompt: 'Photo of the shadow', xp: 70, category: QuestCategory.creative, emoji: '🦇'),
  Quest(id: 'cre_18', title: 'Custom Ringtone', description: 'Change your alarm or ringtone to a completely new audio file you found online.', photoPrompt: 'Screenshot of the settings page', xp: 60, category: QuestCategory.creative, emoji: '🔔'),
  Quest(id: 'cre_19', title: 'Collage', description: 'Cut out pictures/words from an old newspaper/magazine and glue them onto a page.', photoPrompt: 'Photo of the collage', xp: 140, category: QuestCategory.creative, emoji: '✂️'),
  Quest(id: 'cre_20', title: 'The 1-Minute Portrait', description: 'Draw a portrait of the person closest to you, but you only have 60 seconds.', photoPrompt: 'Photo of the rushed drawing', xp: 95, category: QuestCategory.creative, emoji: '👨‍🎨'),

  // ─── ADVENTURE (20) ──────────────────────────────────────────────────────────
  Quest(id: 'adv_01', title: 'Try a Phobia Food', description: 'That thing you always skip on the menu because it sounds sketchy. Order it.', photoPrompt: 'Photo of the challenging dish', xp: 140, category: QuestCategory.adventure, emoji: '🌶️'),
  Quest(id: 'adv_02', title: 'Go Solo', description: 'Go somewhere alone that you\'ve only ever gone with others (restaurant, cinema, etc).', photoPrompt: 'Photo of where you went alone', xp: 180, category: QuestCategory.adventure, emoji: '🧍'),
  Quest(id: 'adv_03', title: 'Night Walk', description: 'Go for a walk after 10 PM. Stick to safely lit areas, but experience the quiet.', photoPrompt: 'Photo of the empty street', xp: 150, category: QuestCategory.adventure, emoji: '🌃'),
  Quest(id: 'adv_04', title: 'Climb a Tree', description: 'Find a sturdy tree and climb it at least a few feet up.', photoPrompt: 'Photo from your vantage point in the tree', xp: 120, category: QuestCategory.adventure, emoji: '🧗'),
  Quest(id: 'adv_05', title: 'Talk Your Way In', description: 'Try to get access to a rooftop, backstage, or vip area just by asking confidently.', photoPrompt: 'Photo proving you got in', xp: 250, category: QuestCategory.adventure, emoji: '🕴️'),
  Quest(id: 'adv_06', title: 'Try a New Sport', description: 'Spend 20 minutes trying a physical activity you don\'t usually do (skating, boxing, dance).', photoPrompt: 'Photo of the equipment / location', xp: 160, category: QuestCategory.adventure, emoji: '🛹'),
  Quest(id: 'adv_07', title: 'Coin Flip Day', description: 'Let a coin flip decide your minor choices for 3 hours (what to eat, left/right, etc).', photoPrompt: 'Photo of the coin', xp: 100, category: QuestCategory.adventure, emoji: '🪙'),
  Quest(id: 'adv_08', title: 'Buy a Mystery Box', description: 'Buy something packaged where you don\'t know exactly what\'s inside.', photoPrompt: 'Photo of the unboxing', xp: 90, category: QuestCategory.adventure, emoji: '🎁'),
  Quest(id: 'adv_09', title: 'Take the Stairs', description: 'Refuse the elevator. Only take stairs today, no matter how many floors.', photoPrompt: 'A very tired selfie in the stairwell', xp: 110, category: QuestCategory.adventure, emoji: '🪜'),
  Quest(id: 'adv_10', title: 'Explore a Ruin', description: 'Walk around an abandoned building or ancient ruin (stay safe!).', photoPrompt: 'Photo of the abandoned site', xp: 200, category: QuestCategory.adventure, emoji: '🏚️'),
  Quest(id: 'adv_11', title: 'Learn a Magic Trick', description: 'Watch a YouTube tutorial and successfully execute a sleight of hand trick to someone.', photoPrompt: 'Photo of the playing deck or prop', xp: 130, category: QuestCategory.adventure, emoji: '🎩'),
  Quest(id: 'adv_12', title: 'The Reverse Commute', description: 'If you usually drive, take the bus. If you usually bus, walk or cycle part of the way.', photoPrompt: 'Photo of your alternative transport method', xp: 140, category: QuestCategory.adventure, emoji: '🚲'),
  Quest(id: 'adv_13', title: 'Brave the Rain', description: 'If it\'s raining, go stand in it for 2 minutes without an umbrella. (If sunny, find a sprinkler).', photoPrompt: 'Photo of you looking very wet', xp: 120, category: QuestCategory.adventure, emoji: '🌧️'),
  Quest(id: 'adv_14', title: 'Ask for a Discount', description: 'At a store/cafe, just politely ask: "Can I get a discount?" See what happens.', photoPrompt: 'Photo of the receipt (or the store)', xp: 170, category: QuestCategory.adventure, emoji: '📉'),
  Quest(id: 'adv_15', title: 'Sleep somewhere Else', description: 'Sleep on the living room floor, or a balcony, or a tent in the yard instead of your bed.', photoPrompt: 'Photo of your makeshift bed', xp: 180, category: QuestCategory.adventure, emoji: '⛺'),
  Quest(id: 'adv_16', title: 'Eat with your Hands', description: 'Eat an entire meal that usually requires utensils using only your bare hands.', photoPrompt: 'Photo of your messy hands', xp: 80, category: QuestCategory.adventure, emoji: '🖐️'),
  Quest(id: 'adv_17', title: 'Say "Yes"', description: 'Say yes to the very next social invitation or request you receive, regardless of what it is.', photoPrompt: 'Photo proving you showed up', xp: 150, category: QuestCategory.adventure, emoji: '✅'),
  Quest(id: 'adv_18', title: 'Spontaneous Travel', description: 'Pack a small day bag and take a train/bus to the next city over just for the afternoon.', photoPrompt: 'Photo showing you in the new city', xp: 300, category: QuestCategory.adventure, emoji: '🚆'),
  Quest(id: 'adv_19', title: 'Wake up at 4 AM', description: 'Set an alarm for 4:00 AM. Wake up, make coffee, and watch the world while it\'s dark.', photoPrompt: 'Photo of the clock at 4 AM', xp: 200, category: QuestCategory.adventure, emoji: '🦇'),
  Quest(id: 'adv_20', title: 'Give a Speech', description: 'Stand on a slight elevation in a park and loudly proclaim something ridiculous to the grass.', photoPrompt: 'Photo of your makeshift podium', xp: 130, category: QuestCategory.adventure, emoji: '📣'),

  // ─── FOOD (20) ───────────────────────────────────────────────────────────────
  Quest(id: 'foo_01', title: 'Spicy Level Up', description: 'Order the spiciest thing on the menu. Don\'t back down.', photoPrompt: 'A very sweaty selfie eating it', xp: 130, category: QuestCategory.food, emoji: '🔥'),
  Quest(id: 'foo_02', title: 'Bake Pizza from Scratch', description: 'Make the dough. Make the sauce. Bake the pizza.', photoPrompt: 'Photo of the rustic irregular pizza', xp: 160, category: QuestCategory.food, emoji: '🍕'),
  Quest(id: 'foo_03', title: 'The Weird Combo', description: 'Eat something that shouldn\'t go together (e.g., Fries dunked in a milkshake).', photoPrompt: 'Photo of the monstrosity before eating it', xp: 80, category: QuestCategory.food, emoji: '🍟'),
  Quest(id: 'foo_04', title: 'Street Food Only', description: 'For one entire day, you can only eat meals bought from street vendors.', photoPrompt: 'Photo of your favorite street food haul', xp: 180, category: QuestCategory.food, emoji: '🍢'),
  Quest(id: 'foo_05', title: 'Eat a Whole Fruit', description: 'Eat an apple or pear, including the core and seeds. Leave nothing but the stem.', photoPrompt: 'Photo of the stem', xp: 60, category: QuestCategory.food, emoji: '🍎'),
  Quest(id: 'foo_06', title: 'Blind Taste Test', description: 'Have a friend blindfold you and feed you 3 things from the kitchen to guess.', photoPrompt: 'Photo of you blindfolded', xp: 110, category: QuestCategory.food, emoji: '🙈'),
  Quest(id: 'foo_07', title: 'Drink Black Coffee', description: 'No sugar. No milk. Just pure dark roast sludge.', photoPrompt: 'Photo of the dark abyss in the mug', xp: 90, category: QuestCategory.food, emoji: '☕'),
  Quest(id: 'foo_08', title: 'Foreign Cuisine', description: 'Order food from a country you have never eaten food from before.', photoPrompt: 'Photo of the dish', xp: 140, category: QuestCategory.food, emoji: '🥘'),
  Quest(id: 'foo_09', title: 'Cook for Someone', description: 'Make a full meal for a friend or family member who didn\'t ask for it.', photoPrompt: 'Photo of them eating your food', xp: 150, category: QuestCategory.food, emoji: '👨‍🍳'),
  Quest(id: 'foo_10', title: 'No Utensil Day', description: 'Survive 24 hours eating everything with chopsticks or your hands.', photoPrompt: 'Photo struggling with chopsticks', xp: 120, category: QuestCategory.food, emoji: '🥢'),
  Quest(id: 'foo_11', title: 'Support the Lemonade Stand', description: 'Find a very tiny local stall/cart running a small operation and buy something.', photoPrompt: 'Photo of the stall', xp: 100, category: QuestCategory.food, emoji: '🍋'),
  Quest(id: 'foo_12', title: 'Learn a Family Recipe', description: 'Ask your mom/grandma/dad for the exact recipe of your favorite childhood dish.', photoPrompt: 'Screenshot of the recipe written down', xp: 110, category: QuestCategory.food, emoji: '🍲'),
  Quest(id: 'foo_13', title: 'Eat a Raw Vegetable', description: 'Eat a whole raw carrot, tomato, or bell pepper like an apple.', photoPrompt: 'Photo mid-crunch', xp: 50, category: QuestCategory.food, emoji: '🥕'),
  Quest(id: 'foo_14', title: 'Make Your Own Dressing', description: 'Make a salad dressing out of olive oil, vinegar, and spices. No bottled stuff.', photoPrompt: 'Photo of the mixed dressing', xp: 70, category: QuestCategory.food, emoji: '🥗'),
  Quest(id: 'foo_15', title: 'Late Night Run', description: 'Go on a specific quest at 1 AM to find a very specific snack.', photoPrompt: 'Photo of the snack secured under streetlights', xp: 130, category: QuestCategory.food, emoji: '🍫'),
  Quest(id: 'foo_16', title: 'Perfect Egg', description: 'Cook a poached or soft-boiled egg perfectly with a runny yolk.', photoPrompt: 'Photo slicing it open', xp: 100, category: QuestCategory.food, emoji: '🥚'),
  Quest(id: 'foo_17', title: 'Try an Exotic Fruit', description: 'Buy a Dragonfruit, Rambutan, or something you\'ve never peeled before.', photoPrompt: 'Photo of the fruit split open', xp: 90, category: QuestCategory.food, emoji: '🐉'),
  Quest(id: 'foo_18', title: 'Zero Food Waste Day', description: 'Finish every single plate today completely clean. No scraps left behind.', photoPrompt: 'Photo of your final spotless dinner plate', xp: 120, category: QuestCategory.food, emoji: '🍽️'),
  Quest(id: 'foo_19', title: 'Make an Elaborate Sandwich', description: 'Build a sandwich with at least 5 different distinct layers.', photoPrompt: 'Cross-section photo of the sandwich', xp: 85, category: QuestCategory.food, emoji: '🥪'),
  Quest(id: 'foo_20', title: 'Only Local Produce', description: 'Eat an entire meal made entirely of ingredients grown within 100km of you.', photoPrompt: 'Photo of the farm-to-table meal', xp: 180, category: QuestCategory.food, emoji: '🚜'),
  
  // ─── RANDOM (20)  ────────────────────────────────────────────────────────────
  Quest(id: 'rnd_01', title: 'Find a Typewriter', description: 'Locate a real mechanical typewriter or antique piece of tech.', photoPrompt: 'Photo of the machine', xp: 130, category: QuestCategory.random, emoji: '📠'),
  Quest(id: 'rnd_02', title: 'Catch a Bug', description: 'Find a cool insect, let it crawl on your hand, then release it.', photoPrompt: 'Photo of the bug on your hand', xp: 110, category: QuestCategory.random, emoji: '🪲'),
  Quest(id: 'rnd_03', title: 'Do a Flip', description: 'Attempt a cartwheel, somersault, or flip on grass.', photoPrompt: 'Action shot of the attempt', xp: 150, category: QuestCategory.random, emoji: '🤸'),
  Quest(id: 'rnd_04', title: 'Find a Four-Leaf Clover', description: 'Spend 10 minutes scanning a patch of clovers to find a mutation.', photoPrompt: 'Photo of the clover', xp: 250, category: QuestCategory.random, emoji: '🍀'),
  Quest(id: 'rnd_05', title: 'Skip Rocks', description: 'Find a flat stone and skip it across a body of water.', photoPrompt: 'Photo of the water ripples', xp: 80, category: QuestCategory.random, emoji: '🪨'),
  Quest(id: 'rnd_06', title: 'Build a Fort', description: 'Use blankets and pillows to build a fort in your living room.', photoPrompt: 'Photo from inside the fort', xp: 120, category: QuestCategory.random, emoji: '⛺'),
  Quest(id: 'rnd_07', title: 'Talk in an Accent', description: 'Order a coffee/item at a shop using a fake accent you don\'t naturally have.', photoPrompt: 'Selfie giving a thumbs up outside the shop', xp: 200, category: QuestCategory.random, emoji: '🎭'),
  Quest(id: 'rnd_08', title: 'Solve a Rubik\'s Cube', description: 'Or at least finish one entire face. Look up a tutorial if you must.', photoPrompt: 'Photo of the cube', xp: 140, category: QuestCategory.random, emoji: '🎲'),
  Quest(id: 'rnd_09', title: 'Fly a Kite', description: 'Buy, build, or borrow a kite and successfully get it airborne.', photoPrompt: 'Photo of the kite in the sky', xp: 160, category: QuestCategory.random, emoji: '🪁'),
  Quest(id: 'rnd_10', title: 'Find your Name', description: 'Find your exact first name written on something in public (not your own ID).', photoPrompt: 'Photo of the text', xp: 90, category: QuestCategory.random, emoji: '🏷️'),
  Quest(id: 'rnd_11', title: 'Spot a License Plate', description: 'Stare at cars until you find a license plate with the number 777 or 999.', photoPrompt: 'Photo of the license plate', xp: 110, category: QuestCategory.random, emoji: '🚗'),
  Quest(id: 'rnd_12', title: 'Balance a Spoon', description: 'Balance a spoon horizontally on the end of your nose for 3 seconds.', photoPrompt: 'A very silly selfie making the attempt', xp: 80, category: QuestCategory.random, emoji: '🥄'),
  Quest(id: 'rnd_13', title: 'Play a Prank', description: 'Play a completely harmless, confusing prank on a roommate or family member.', photoPrompt: 'Photo of the prank setup', xp: 100, category: QuestCategory.random, emoji: '🃏'),
  Quest(id: 'rnd_14', title: 'Make an Animal Friend', description: 'Get a stray dog, cat, or bird to willingly approach you for food/pets.', photoPrompt: 'Photo of the animal interacting with you', xp: 140, category: QuestCategory.random, emoji: '🐾'),
  Quest(id: 'rnd_15', title: 'Catch Sunrise AND Sunset', description: 'See both the sunrise and the sunset in the exact same day.', photoPrompt: 'Collage or side-by-side photo', xp: 300, category: QuestCategory.random, emoji: '🌞'),
  Quest(id: 'rnd_16', title: 'Write a Letter', description: 'Write a physical letter to your future self 1 year from now. Seal it.', photoPrompt: 'Photo of the sealed envelope', xp: 120, category: QuestCategory.random, emoji: '✉️'),
  Quest(id: 'rnd_17', title: 'Find a Payphone', description: 'Locate a public payphone that still physically exists on a street.', photoPrompt: 'Photo holding the phone receiver', xp: 150, category: QuestCategory.random, emoji: '☎️'),
  Quest(id: 'rnd_18', title: 'Pet 3 Dogs', description: 'Successfully ask permission and pet 3 different strangers\' dogs today.', photoPrompt: 'Photo of Dog #3', xp: 130, category: QuestCategory.random, emoji: '🐕'),
  Quest(id: 'rnd_19', title: 'Paper Airplane Test', description: 'Fold a paper airplane and throw it from a high place to see how far it goes.', photoPrompt: 'Photo of the plane mid-flight', xp: 80, category: QuestCategory.random, emoji: '✈️'),
  Quest(id: 'rnd_20', title: 'Juggle', description: 'Successfully juggle 3 small objects for exactly 4 seconds before dropping them.', photoPrompt: 'Photo of the 3 objects you used', xp: 120, category: QuestCategory.random, emoji: '🤹'),
];
