// Mocks generated by Mockito 5.4.6 from annotations
// in verasso/test/features/auth/presentation/auth_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:supabase_flutter/supabase_flutter.dart' as _i2;
import 'package:verasso/core/security/offline_security_service.dart' as _i8;
import 'package:verasso/core/security/token_storage_service.dart' as _i7;
import 'package:verasso/features/auth/data/auth_repository.dart' as _i5;
import 'package:verasso/features/auth/domain/auth_service.dart' as _i4;
import 'package:verasso/features/auth/domain/mfa_models.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSupabaseClient_0 extends _i1.SmartFake
    implements _i2.SupabaseClient {
  _FakeSupabaseClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMfaChallenge_1 extends _i1.SmartFake implements _i3.MfaChallenge {
  _FakeMfaChallenge_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthResult_2 extends _i1.SmartFake implements _i4.AuthResult {
  _FakeAuthResult_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i5.AuthRepository {
  @override
  _i6.Stream<_i4.DomainAuthUser?> get authStateChanges => (super.noSuchMethod(
        Invocation.getter(#authStateChanges),
        returnValue: _i6.Stream<_i4.DomainAuthUser?>.empty(),
        returnValueForMissingStub: _i6.Stream<_i4.DomainAuthUser?>.empty(),
      ) as _i6.Stream<_i4.DomainAuthUser?>);

  @override
  _i2.SupabaseClient get supabaseClient => (super.noSuchMethod(
        Invocation.getter(#supabaseClient),
        returnValue: _FakeSupabaseClient_0(
          this,
          Invocation.getter(#supabaseClient),
        ),
        returnValueForMissingStub: _FakeSupabaseClient_0(
          this,
          Invocation.getter(#supabaseClient),
        ),
      ) as _i2.SupabaseClient);

  @override
  _i6.Future<void> challengeAndVerify({
    required String? factorId,
    required String? code,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #challengeAndVerify,
          [],
          {
            #factorId: factorId,
            #code: code,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i3.MfaChallenge> challengeMFA({required String? factorId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #challengeMFA,
          [],
          {#factorId: factorId},
        ),
        returnValue: _i6.Future<_i3.MfaChallenge>.value(_FakeMfaChallenge_1(
          this,
          Invocation.method(
            #challengeMFA,
            [],
            {#factorId: factorId},
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i3.MfaChallenge>.value(_FakeMfaChallenge_1(
          this,
          Invocation.method(
            #challengeMFA,
            [],
            {#factorId: factorId},
          ),
        )),
      ) as _i6.Future<_i3.MfaChallenge>);

  @override
  _i6.Future<_i3.MfaEnrollment?> enrollMFA() => (super.noSuchMethod(
        Invocation.method(
          #enrollMFA,
          [],
        ),
        returnValue: _i6.Future<_i3.MfaEnrollment?>.value(),
        returnValueForMissingStub: _i6.Future<_i3.MfaEnrollment?>.value(),
      ) as _i6.Future<_i3.MfaEnrollment?>);

  @override
  _i6.Future<List<dynamic>> listFactors() => (super.noSuchMethod(
        Invocation.method(
          #listFactors,
          [],
        ),
        returnValue: _i6.Future<List<dynamic>>.value(<dynamic>[]),
        returnValueForMissingStub: _i6.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i6.Future<List<dynamic>>);

  @override
  _i6.Future<void> resetPasswordForEmail({required String? email}) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPasswordForEmail,
          [],
          {#email: email},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i4.AuthResult> signInWithEmail({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithEmail,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i6.Future<_i4.AuthResult>.value(_FakeAuthResult_2(
          this,
          Invocation.method(
            #signInWithEmail,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i4.AuthResult>.value(_FakeAuthResult_2(
          this,
          Invocation.method(
            #signInWithEmail,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
      ) as _i6.Future<_i4.AuthResult>);

  @override
  _i6.Future<void> signInWithOAuth(_i2.OAuthProvider? provider) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithOAuth,
          [provider],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> signInWithOtp({
    required String? email,
    bool? isWeb = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithOtp,
          [],
          {
            #email: email,
            #isWeb: isWeb,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> signInWithPhone({required String? phone}) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithPhone,
          [],
          {#phone: phone},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i4.AuthResult> signUpWithEmail({
    required String? email,
    required String? password,
    String? username,
    Map<String, dynamic>? data,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUpWithEmail,
          [],
          {
            #email: email,
            #password: password,
            #username: username,
            #data: data,
          },
        ),
        returnValue: _i6.Future<_i4.AuthResult>.value(_FakeAuthResult_2(
          this,
          Invocation.method(
            #signUpWithEmail,
            [],
            {
              #email: email,
              #password: password,
              #username: username,
              #data: data,
            },
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i4.AuthResult>.value(_FakeAuthResult_2(
          this,
          Invocation.method(
            #signUpWithEmail,
            [],
            {
              #email: email,
              #password: password,
              #username: username,
              #data: data,
            },
          ),
        )),
      ) as _i6.Future<_i4.AuthResult>);

  @override
  _i6.Future<void> unenrollMFA({required String? factorId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #unenrollMFA,
          [],
          {#factorId: factorId},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateUserPassword({required String? password}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserPassword,
          [],
          {#password: password},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i4.AuthResult?> verifyMFA({
    required String? factorId,
    required String? challengeId,
    required String? code,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyMFA,
          [],
          {
            #factorId: factorId,
            #challengeId: challengeId,
            #code: code,
          },
        ),
        returnValue: _i6.Future<_i4.AuthResult?>.value(),
        returnValueForMissingStub: _i6.Future<_i4.AuthResult?>.value(),
      ) as _i6.Future<_i4.AuthResult?>);

  @override
  _i6.Future<_i4.AuthResult?> verifyOtp({
    required String? token,
    required dynamic type,
    String? email,
    String? phone,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyOtp,
          [],
          {
            #token: token,
            #type: type,
            #email: email,
            #phone: phone,
          },
        ),
        returnValue: _i6.Future<_i4.AuthResult?>.value(),
        returnValueForMissingStub: _i6.Future<_i4.AuthResult?>.value(),
      ) as _i6.Future<_i4.AuthResult?>);

  @override
  _i6.Future<T?> handleError<T>({
    required _i6.Future<T> Function()? operation,
    required String? context,
    String? userMessage,
    bool? reportToSentry = false,
    bool? rethrowError = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #handleError,
          [],
          {
            #operation: operation,
            #context: context,
            #userMessage: userMessage,
            #reportToSentry: reportToSentry,
            #rethrowError: rethrowError,
          },
        ),
        returnValue: _i6.Future<T?>.value(),
        returnValueForMissingStub: _i6.Future<T?>.value(),
      ) as _i6.Future<T?>);

  @override
  void logError(
    dynamic error,
    StackTrace? stackTrace,
    String? context, {
    bool? critical = false,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #logError,
          [
            error,
            stackTrace,
            context,
          ],
          {#critical: critical},
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [TokenStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTokenStorageService extends _i1.Mock
    implements _i7.TokenStorageService {
  @override
  _i6.Future<void> clearTokens() => (super.noSuchMethod(
        Invocation.method(
          #clearTokens,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<Map<String, String?>> getAllStoredData() => (super.noSuchMethod(
        Invocation.method(
          #getAllStoredData,
          [],
        ),
        returnValue:
            _i6.Future<Map<String, String?>>.value(<String, String?>{}),
        returnValueForMissingStub:
            _i6.Future<Map<String, String?>>.value(<String, String?>{}),
      ) as _i6.Future<Map<String, String?>>);

  @override
  _i6.Future<String?> getRefreshToken() => (super.noSuchMethod(
        Invocation.method(
          #getRefreshToken,
          [],
        ),
        returnValue: _i6.Future<String?>.value(),
        returnValueForMissingStub: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);

  @override
  _i6.Future<String?> getUserEmail() => (super.noSuchMethod(
        Invocation.method(
          #getUserEmail,
          [],
        ),
        returnValue: _i6.Future<String?>.value(),
        returnValueForMissingStub: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);

  @override
  _i6.Future<String?> getUserId() => (super.noSuchMethod(
        Invocation.method(
          #getUserId,
          [],
        ),
        returnValue: _i6.Future<String?>.value(),
        returnValueForMissingStub: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);

  @override
  _i6.Future<bool> hasStoredCredentials() => (super.noSuchMethod(
        Invocation.method(
          #hasStoredCredentials,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
        returnValueForMissingStub: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> isSessionValid() => (super.noSuchMethod(
        Invocation.method(
          #isSessionValid,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
        returnValueForMissingStub: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<_i2.AuthResponse?> refreshSession(_i2.SupabaseClient? client) =>
      (super.noSuchMethod(
        Invocation.method(
          #refreshSession,
          [client],
        ),
        returnValue: _i6.Future<_i2.AuthResponse?>.value(),
        returnValueForMissingStub: _i6.Future<_i2.AuthResponse?>.value(),
      ) as _i6.Future<_i2.AuthResponse?>);

  @override
  _i6.Future<void> saveRefreshToken(String? refreshToken) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveRefreshToken,
          [refreshToken],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> saveSessionExpiry(DateTime? expiry) => (super.noSuchMethod(
        Invocation.method(
          #saveSessionExpiry,
          [expiry],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> saveUserEmail(String? email) => (super.noSuchMethod(
        Invocation.method(
          #saveUserEmail,
          [email],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> saveUserId(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #saveUserId,
          [userId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [OfflineSecurityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOfflineSecurityService extends _i1.Mock
    implements _i8.OfflineSecurityService {
  @override
  _i6.Future<void> clearIdentityHint() => (super.noSuchMethod(
        Invocation.method(
          #clearIdentityHint,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<String?> getLastKnownEmail() => (super.noSuchMethod(
        Invocation.method(
          #getLastKnownEmail,
          [],
        ),
        returnValue: _i6.Future<String?>.value(),
        returnValueForMissingStub: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);

  @override
  _i6.Future<bool> hasIdentityHint() => (super.noSuchMethod(
        Invocation.method(
          #hasIdentityHint,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
        returnValueForMissingStub: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<void> setIdentityHint(String? email) => (super.noSuchMethod(
        Invocation.method(
          #setIdentityHint,
          [email],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}
