// Mocks generated by Mockito 5.4.6 from annotations
// in verasso/test/integration/auth_flow_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:supabase_flutter/supabase_flutter.dart' as _i2;
import 'package:verasso/features/auth/data/auth_repository.dart' as _i5;
import 'package:verasso/features/auth/domain/auth_service.dart' as _i4;
import 'package:verasso/features/auth/domain/mfa_models.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSupabaseClient_0 extends _i1.SmartFake
    implements _i2.SupabaseClient {
  _FakeSupabaseClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMfaChallenge_1 extends _i1.SmartFake implements _i3.MfaChallenge {
  _FakeMfaChallenge_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthResult_2 extends _i1.SmartFake implements _i4.AuthResult {
  _FakeAuthResult_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i5.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Stream<_i4.DomainAuthUser?> get authStateChanges => (super.noSuchMethod(
        Invocation.getter(#authStateChanges),
        returnValue: _i6.Stream<_i4.DomainAuthUser?>.empty(),
      ) as _i6.Stream<_i4.DomainAuthUser?>);

  @override
  _i2.SupabaseClient get supabaseClient => (super.noSuchMethod(
        Invocation.getter(#supabaseClient),
        returnValue: _FakeSupabaseClient_0(
          this,
          Invocation.getter(#supabaseClient),
        ),
      ) as _i2.SupabaseClient);

  @override
  _i6.Future<void> challengeAndVerify({
    required String? factorId,
    required String? code,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #challengeAndVerify,
          [],
          {
            #factorId: factorId,
            #code: code,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i3.MfaChallenge> challengeMFA({required String? factorId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #challengeMFA,
          [],
          {#factorId: factorId},
        ),
        returnValue: _i6.Future<_i3.MfaChallenge>.value(_FakeMfaChallenge_1(
          this,
          Invocation.method(
            #challengeMFA,
            [],
            {#factorId: factorId},
          ),
        )),
      ) as _i6.Future<_i3.MfaChallenge>);

  @override
  _i6.Future<_i3.MfaEnrollment?> enrollMFA() => (super.noSuchMethod(
        Invocation.method(
          #enrollMFA,
          [],
        ),
        returnValue: _i6.Future<_i3.MfaEnrollment?>.value(),
      ) as _i6.Future<_i3.MfaEnrollment?>);

  @override
  _i6.Future<List<dynamic>> listFactors() => (super.noSuchMethod(
        Invocation.method(
          #listFactors,
          [],
        ),
        returnValue: _i6.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i6.Future<List<dynamic>>);

  @override
  _i6.Future<void> resetPasswordForEmail({required String? email}) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPasswordForEmail,
          [],
          {#email: email},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i4.AuthResult> signInWithEmail({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithEmail,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i6.Future<_i4.AuthResult>.value(_FakeAuthResult_2(
          this,
          Invocation.method(
            #signInWithEmail,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
      ) as _i6.Future<_i4.AuthResult>);

  @override
  _i6.Future<void> signInWithOAuth(_i2.OAuthProvider? provider) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithOAuth,
          [provider],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> signInWithOtp({
    required String? email,
    bool? isWeb = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithOtp,
          [],
          {
            #email: email,
            #isWeb: isWeb,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> signInWithPhone({required String? phone}) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithPhone,
          [],
          {#phone: phone},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i4.AuthResult> signUpWithEmail({
    required String? email,
    required String? password,
    String? username,
    Map<String, dynamic>? data,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUpWithEmail,
          [],
          {
            #email: email,
            #password: password,
            #username: username,
            #data: data,
          },
        ),
        returnValue: _i6.Future<_i4.AuthResult>.value(_FakeAuthResult_2(
          this,
          Invocation.method(
            #signUpWithEmail,
            [],
            {
              #email: email,
              #password: password,
              #username: username,
              #data: data,
            },
          ),
        )),
      ) as _i6.Future<_i4.AuthResult>);

  @override
  _i6.Future<void> unenrollMFA({required String? factorId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #unenrollMFA,
          [],
          {#factorId: factorId},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateUserPassword({required String? password}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserPassword,
          [],
          {#password: password},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i4.AuthResult?> verifyMFA({
    required String? factorId,
    required String? challengeId,
    required String? code,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyMFA,
          [],
          {
            #factorId: factorId,
            #challengeId: challengeId,
            #code: code,
          },
        ),
        returnValue: _i6.Future<_i4.AuthResult?>.value(),
      ) as _i6.Future<_i4.AuthResult?>);

  @override
  _i6.Future<_i4.AuthResult?> verifyOtp({
    required String? token,
    required dynamic type,
    String? email,
    String? phone,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyOtp,
          [],
          {
            #token: token,
            #type: type,
            #email: email,
            #phone: phone,
          },
        ),
        returnValue: _i6.Future<_i4.AuthResult?>.value(),
      ) as _i6.Future<_i4.AuthResult?>);

  @override
  _i6.Future<T?> handleError<T>({
    required _i6.Future<T> Function()? operation,
    required String? context,
    String? userMessage,
    bool? reportToSentry = false,
    bool? rethrowError = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #handleError,
          [],
          {
            #operation: operation,
            #context: context,
            #userMessage: userMessage,
            #reportToSentry: reportToSentry,
            #rethrowError: rethrowError,
          },
        ),
        returnValue: _i6.Future<T?>.value(),
      ) as _i6.Future<T?>);

  @override
  void logError(
    dynamic error,
    StackTrace? stackTrace,
    String? context, {
    bool? critical = false,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #logError,
          [
            error,
            stackTrace,
            context,
          ],
          {#critical: critical},
        ),
        returnValueForMissingStub: null,
      );
}
